language: php

php: [5.3, 5.4, 5.5, 5.6, hhvm]

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: CRAWLER_VERSION='2.3.*'
    - php: 5.5
      env: CRAWLER_VERSION='2.6.*@dev'

env:
  global:
    - WEB_FIXTURES_HOST=http://localhost
    - WEB_FIXTURES_BROWSER=firefox

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 4

  - curl -L http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar > selenium.jar
  - sudo ln -s /usr/lib/firefox/firefox /usr/lib/firefox/firefox-bin
  - PATH=$PATH:/usr/lib/firefox java -jar selenium.jar > /dev/null 2>&1 &
  - sleep 4

  - sh -c 'if [ "$CRAWLER_VERSION" != "" ]; then composer require --no-update symfony/dom-crawler=$CRAWLER_VERSION; fi;'
  - composer install --dev --prefer-source

  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5
  - sudo sed -i -e "s,/var/www,$(pwd)/vendor/behat/mink/driver-testsuite/web-fixtures,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart


script: phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
